### ISSUE TITLE
How can set bootstrap version ?

### ISSUE THREAD

**Issue by paskuale75** [buttflattery/yii2-formwizard#42] opened 2019-10-19 11:47 UTC
Hi, thanks for this amazing extension, 
I load bootstrap 3.0 from composer.json but this widget add a bootstrap.css file that corrupts my css.

**Comment by buttflattery** [comment] 2019-10-19 13:05
hello @paskuale75 ,the extension detects if you are using the `yiisoft/yii2-bootstrap` or `yiisoft/yii2-bootstrap4` and loads the appropriate assets for the extension. It will check first the `"yiisoft/yii2-bootstrap4"` if it exists then it will load `bootstrap4` resources otherwise it will fall back to use `bootstrap3`. So make sure you are following the correct guide to use the `"yiisoft/yii2-bootstrap4"` and remove the `"yiisoft/yii2-bootstrap": "~2.0.0"`, from you `composer.json` and change the `minimum-stability:"dev"` [here](https://github.com/yiisoft/yii2-bootstrap4/blob/master/docs/guide/README.md) is the complete guide.

**Comment by buttflattery** [comment] 2019-10-19 15:53
apart from that what do you mean when you say 
> this widget add a bootstrap.css file that corrupts my css

**Comment by paskuale75** [comment] 2019-10-19 16:11
yes you are right, an excellent strategy to automatically detect the bootstrap version, but I've only bs4 in my composer ... why return me this :
```
Failed to instantiate component or class "yii\bootstrap\BootstrapAsset".
↵
Caused by: ReflectionException
Class yii\bootstrap\BootstrapAsset does not exist
```

**Comment by paskuale75** [comment] 2019-10-19 16:15
founded ... extra asset with bs3 dependency, sorry my mistake ;)

**Comment by paskuale75** [comment] 2019-10-19 16:18
am I forced to use both the bs3 + bs4 version due to an extension, can I force the use of bs3 with the formWizard?

**Comment by buttflattery** [comment] 2019-10-19 16:30
not getting exactly what you are saying using both bs3 and bs4 isnt an advisable thing to do even if you are using this extension or not, if you are still looking to do something like forcing the extension form-wzard to use bs3 anyway you can extend override the [`registerScripts()`](https://github.com/buttflattery/yii2-formwizard/blob/master/src/FormWizard.php#L977) method to register the `bs3Assets` class only.  But i havent tested any such thing as the `_bsVersion` property is set inside the `_setDefaults` which is private

**Comment by paskuale75** [comment] 2019-10-19 16:47
many thanks @buttflattery

**Comment by paskuale75** [comment] 2019-10-19 17:41
@buttflattery I followed your advice, I forked the repository and disabled the bs4 case, but I still find myself a bootstrap.css twice why?

**Comment by buttflattery** [comment] 2019-10-19 17:44
if you are forking the repo then i must say you should change [this](https://github.com/buttflattery/yii2-formwizard/blob/master/src/FormWizard.php#L473) line rather than overriding the `registerScripts()` and there isnt any other part where it adds the bootstrap assets other than these functions i specified,

**Comment by buttflattery** [comment] 2020-01-19 03:40
@paskuale75  i just released a new version with 2 new features, one of which include forcing bootstrap version with option simple as `"forceBsVersion"=>FormWizard::BS_3`

**Comment by buttflattery** [comment] 2020-01-19 17:30
Duplicate of #49

**Closed by buttflattery** 2020-01-19 17:30 UTC
Labels: question
